---
version: "3.7"

services:

  inference-ops-db:
    container_name: inference-ops-db
    image: postgres:13.23-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      # Persist data that is stored in db after
      # container is shutdown.
      - inference-ops_data:/var/lib/postgresql/data/
    networks:
      - inference-ops-net
    # TODO: comment this after the Django server is dockerized
    ports:
      - "5432:5432"
  
volumes:
  inference-ops_data:

networks:
  inference-ops-net: